### ISSUE TITLE
Reduce font size of social card title

### ISSUE THREAD

**Issue by eugeneyan** [parlance-labs/applied-llms#7]
Currently, the site title is getting truncated in the social card.

![image](https://github.com/parlance-labs/applied-llms/assets/6831355/76deb6f9-1041-4d0f-a619-8eade2531bd9)

Did some research and it doesn't seem like mkdocs supports allowing users to tweak the font sizes for [now](https://github.com/squidfunk/mkdocs-material/discussions/3478). Although the insider's edition (for sponsors only) allows [custom cards](https://squidfunk.github.io/mkdocs-material/tutorials/social/custom/), it's unclear if allows tweaking of font size.

To revisit.

**Comment by hamelsmu** [comment]
I fixed this by using Google Slides :p See social card now (instructions in the README) - I know its low tech solution :) 

Will close this, feel free to reopen if necessary
