### ISSUE TITLE
Broken Link (typo)

### ISSUE THREAD

**Issue by yismailuofa** [parlance-labs/applied-llms#8]
https://github.com/parlance-labs/applied-llms/blob/046f119a9feefd6b08a048b733da2ce19abbbf1d/_mkdocs/site/index.html#L1480

Link is broken here, I think the href just needs to be updated like:
`href="https://twitter.com/mattshumer_/status/1770823530394833242"`

**Comment by eugeneyan** [comment]
Thanks for letting up know—fixed both links in the paragraph!
